export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  rating: number;
  reviews: number;
  badge?: string;
  badgeColor?: 'orange' | 'red';
  category: string;
}

export const dealProducts: Product[] = [
  {
    id: '1',
    name: 'Sữa Rửa Mặt Yehwadam Làm Sạch Ngừa Lão Hóa Da Hwansaenggo Serum Infused Foaming Cleanser 150ml',
    price: 199000,
    originalPrice: 299000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.5,
    reviews: 128,
    badge: '-33%',
    badgeColor: 'orange',
    category: 'face-care',
  },
  {
    id: '2',
    name: 'Sữa Rửa Mặt Yehwadam Dưỡng Ẩm Deep Moisturizing Foaming Cleanser 150ml',
    price: 249000,
    originalPrice: 349000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.8,
    reviews: 256,
    badge: '-28%',
    badgeColor: 'orange',
    category: 'masks',
  },
  {
    id: '3',
    name: 'Sữa Rửa Mặt Làm Sạch Da THE FACE SHOP Rice Water Bright Cleansing Foam 300ml',
    price: 189000,
    originalPrice: 279000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.6,
    reviews: 189,
    badge: '-32%',
    badgeColor: 'orange',
    category: 'toners',
  },
  {
    id: '4',
    name: 'Cleansing Foam',
    price: 149000,
    originalPrice: 219000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.7,
    reviews: 342,
    badge: '-32%',
    badgeColor: 'orange',
    category: 'cleansers',
  },
  {
    id: '5',
    name: 'Night Sleeping Mask',
    price: 229000,
    originalPrice: 329000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.9,
    reviews: 421,
    badge: '-30%',
    badgeColor: 'orange',
    category: 'masks',
  },
];

export const topPickProducts: Product[] = [
  {
    id: '6',
    name: 'Gold Snail Eye Cream',
    price: 279000,
    originalPrice: 399000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.8,
    reviews: 567,
    badge: '-30%',
    badgeColor: 'orange',
    category: 'eye-care',
  },
  {
    id: '7',
    name: 'Sunscreen SPF 50',
    price: 189000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.6,
    reviews: 234,
    category: 'sun-care',
  },
  {
    id: '8',
    name: 'Hydrating Essence',
    price: 199000,
    originalPrice: 299000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.7,
    reviews: 345,
    badge: '-33%',
    badgeColor: 'orange',
    category: 'essence',
  },
  {
    id: '9',
    name: 'BB Cream 23 Natural',
    price: 159000,
    originalPrice: 229000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.9,
    reviews: 678,
    badge: '-30%',
    badgeColor: 'orange',
    category: 'base',
  },
  {
    id: '10',
    name: 'Lip Tint 01 Cherry',
    price: 89000,
    originalPrice: 129000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.5,
    reviews: 412,
    badge: '-31%',
    badgeColor: 'orange',
    category: 'lips',
  },
  {
    id: '11',
    name: 'Setting Spray 100ml',
    price: 119000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.4,
    reviews: 156,
    category: 'setting',
  },
];

export const bodyCareProducts: Product[] = [
  {
    id: '12',
    name: 'Body Lotion 300ml',
    price: 159000,
    originalPrice: 239000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.6,
    reviews: 289,
    badge: '-33%',
    badgeColor: 'orange',
    category: 'body-care',
  },
  {
    id: '13',
    name: 'Body Scrub 250ml',
    price: 139000,
    originalPrice: 199000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.5,
    reviews: 167,
    badge: '-30%',
    badgeColor: 'orange',
    category: 'body-care',
  },
  {
    id: '14',
    name: 'Hand Cream Set (3pcs)',
    price: 179000,
    originalPrice: 259000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.7,
    reviews: 334,
    badge: '-31%',
    badgeColor: 'orange',
    category: 'hand-care',
  },
  {
    id: '15',
    name: 'Bath Bomb Set (5pcs)',
    price: 199000,
    originalPrice: 289000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.8,
    reviews: 445,
    badge: '-31%',
    badgeColor: 'orange',
    category: 'bath',
  },
  {
    id: '16',
    name: 'Body Mist 100ml',
    price: 129000,
    originalPrice: 189000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.4,
    reviews: 98,
    badge: '-32%',
    badgeColor: 'orange',
    category: 'body-care',
  },
];

export const skinCareProducts: Product[] = [
  {
    id: '17',
    name: 'Serum Vitamin C 30ml',
    price: 289000,
    originalPrice: 429000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.9,
    reviews: 612,
    badge: '-33%',
    badgeColor: 'orange',
    category: 'serum',
  },
  {
    id: '18',
    name: 'Toner Pads (100pcs)',
    price: 169000,
    originalPrice: 249000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.6,
    reviews: 289,
    badge: '-32%',
    badgeColor: 'orange',
    category: 'toners',
  },
  {
    id: '19',
    name: 'Acne Patch (24pcs)',
    price: 99000,
    originalPrice: 149000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.7,
    reviews: 523,
    badge: '-33%',
    badgeColor: 'orange',
    category: 'treatments',
  },
  {
    id: '20',
    name: 'Moisturizer 50ml',
    price: 199000,
    originalPrice: 299000,
    image: '/placeholder.svg?height=200&width=200',
    rating: 4.8,
    reviews: 401,
    badge: '-33%',
    badgeColor: 'orange',
    category: 'moisturizers',
  },
];
